/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsTypeRouteImport } from './routes/products/$type'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as BrandsBrandIdRouteImport } from './routes/brands/$brandId'
import { Route as ProductsTypeBrandRouteImport } from './routes/products/$type/$brand'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTypeRoute = ProductsTypeRouteImport.update({
  id: '/products/$type',
  path: '/products/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTypeBrandRoute = ProductsTypeBrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => ProductsTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/products/$type': typeof ProductsTypeRouteWithChildren
  '/products': typeof ProductsIndexRoute
  '/products/$type/$brand': typeof ProductsTypeBrandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/products/$type': typeof ProductsTypeRouteWithChildren
  '/products': typeof ProductsIndexRoute
  '/products/$type/$brand': typeof ProductsTypeBrandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/products/$type': typeof ProductsTypeRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$type/$brand': typeof ProductsTypeBrandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/brands/$brandId'
    | '/product/$productId'
    | '/products/$type'
    | '/products'
    | '/products/$type/$brand'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/brands/$brandId'
    | '/product/$productId'
    | '/products/$type'
    | '/products'
    | '/products/$type/$brand'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/brands/$brandId'
    | '/product/$productId'
    | '/products/$type'
    | '/products/'
    | '/products/$type/$brand'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ProductsTypeRoute: typeof ProductsTypeRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$type': {
      id: '/products/$type'
      path: '/products/$type'
      fullPath: '/products/$type'
      preLoaderRoute: typeof ProductsTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$type/$brand': {
      id: '/products/$type/$brand'
      path: '/$brand'
      fullPath: '/products/$type/$brand'
      preLoaderRoute: typeof ProductsTypeBrandRouteImport
      parentRoute: typeof ProductsTypeRoute
    }
  }
}

interface ProductsTypeRouteChildren {
  ProductsTypeBrandRoute: typeof ProductsTypeBrandRoute
}

const ProductsTypeRouteChildren: ProductsTypeRouteChildren = {
  ProductsTypeBrandRoute: ProductsTypeBrandRoute,
}

const ProductsTypeRouteWithChildren = ProductsTypeRoute._addFileChildren(
  ProductsTypeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ProductsTypeRoute: ProductsTypeRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
